### ISSUE TITLE
[BUG] out of vocabulary when saving

### ISSUE THREAD

**Issue by huyiwen** [1kkiRen/Tokenizer-Changer#1]
Thanks for the repository. However, I encountered an out-of-vocabulary issue when saving the modified tokenizer:

```
Traceback (most recent call last):
  File "/Users/huyiwen/Documents/2024_Q3/modify_tokenizer/try_tokenizerchanger.py", line 9, in <module>
    changer.save_tokenizer("merge_try_tf_2853")
  File "/Users/huyiwen/miniconda3/lib/python3.11/site-packages/TokenizerChanger/tokenizer_changer.py", line 323, in save_tokenizer
    self.tokenizer.backend_tokenizer.model = model_class(
                                             ^^^^^^^^^^^^
Exception: Error while initializing BPE: Token `☀` out of vocabulary
```

Here's my code:

```
from TokenizerChanger import TokenizerChanger
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("openbmb/minicpm-2b-sft-bf16")

changer = TokenizerChanger(tokenizer)
changer.delete_k_least_frequent_tokens(k=2853)
changer.save_tokenizer("merge_try_tf_2853")
```

Do you have any idea?

**Comment by 1kkiRen** [comment]
Hi! Weird thing. All works correctly on my lap. Do you use the latest version of the lib?
![изображение](https://github.com/user-attachments/assets/97ab73a1-92e1-475b-9373-c1b51a876ddc)

**Comment by huyiwen** [comment]
Thanks for the reply, I'll check it again later.
