### ISSUE TITLE
[BUG] delete_merges() fail in Qwen2 tokenizer

### ISSUE THREAD

**Issue by lifelongeeek** [1kkiRen/Tokenizer-Changer#2]
**Describe the bug**
delete_merges() fail in Qwen2 tokenizer

**To Reproduce**
```
from transformers import AutoTokenizer

from TokenizerChanger import TokenizerChanger

tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-7B-Instruct")

changer = TokenizerChanger(tokenizer=tokenizer)

num_delete_vocab = int(len(tokenizer) * 0.1)  # 10% remove
changer.delete_k_least_frequent_tokens(k=num_delete_vocab)
```

**Expected behavior**
Vocab is successfully removed

**Screenshots**
```
tokenizer_config.json: 100%|█████████████████████████████████████████████████| 1.29k/1.29k [00:00<00:00, 2.68MB/s]
vocab.json: 100%|████████████████████████████████████████████████████████████| 2.78M/2.78M [00:01<00:00, 2.65MB/s]
merges.txt: 100%|████████████████████████████████████████████████████████████| 1.67M/1.67M [00:00<00:00, 9.31MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████| 7.03M/7.03M [00:01<00:00, 5.28MB/s]
Finding unwanted tokens:  10%|███▉                                    | 15164/151643 [00:00<00:00, 5358249.86it/s]
Deleting unwanted words: 100%|█████████████████████████████████████████| 15164/15164 [00:00<00:00, 3344679.53it/s]
Traceback (most recent call last):
  File "/Users/geonminkim/Nota/Tokenizer-Changer/reduce_qwen2_vocab.py", line 10, in <module>
    changer.delete_k_least_frequent_tokens(k=num_delete_vocab)
  File "/Users/geonminkim/Nota/Tokenizer-Changer/TokenizerChanger/tokenizer_changer.py", line 386, in delete_k_least_frequent_tokens
    self.delete_tokens(include_substrings=False,
  File "/Users/geonminkim/Nota/Tokenizer-Changer/TokenizerChanger/tokenizer_changer.py", line 344, in delete_tokens
    self.delete_merges()
  File "/Users/geonminkim/Nota/Tokenizer-Changer/TokenizerChanger/tokenizer_changer.py", line 265, in delete_merges
    processed_merges = [(re.sub(pattern, "", merge), merge)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/geonminkim/Nota/Tokenizer-Changer/TokenizerChanger/tokenizer_changer.py", line 265, in <listcomp>
    processed_merges = [(re.sub(pattern, "", merge), merge)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'list'
```

**Env (please complete the following information):**
 - OS: MacOS
 - Python: 3.10

**Additional context**

**Comment by 1kkiRen** [comment]
Hi, @lifelongeeek ! Thank you for highlighting this issue! I guess it works correctly now.
